"""Render the CSV leaderboard as a GitHub-friendly Markdown table."""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPOSITORY_ROOT / "validation" / "leaderboard.csv"
DEFAULT_SORT_COLUMN = "mean_prauc"


def _numeric_sort_key(row: dict[str, str], column: str) -> tuple[bool, float]:
    raw_value = row.get(column, "").strip()
    if not raw_value:
        return True, -math.inf
    try:
        value = float(raw_value)
    except ValueError as error:
        raise ValueError(f"{column} must contain numeric values, found {raw_value!r}") from error
    if not math.isfinite(value):
        raise ValueError(f"{column} must contain finite values, found {raw_value!r}")
    return False, -value


def _markdown_cell(value: str) -> str:
    if not value:
        return "—"
    return value.replace("|", r"\|").replace("\r\n", "<br>").replace("\n", "<br>")


def render_leaderboard(
    csv_path: Path,
    markdown_path: Path | None = None,
    *,
    sort_by: str = DEFAULT_SORT_COLUMN,
) -> Path:
    """Convert a leaderboard CSV to Markdown, sorted by a descending score."""
    if markdown_path is None:
        markdown_path = csv_path.with_suffix(".md")

    with csv_path.open(newline="", encoding="utf-8") as source:
        reader = csv.DictReader(source)
        if not reader.fieldnames:
            raise ValueError(f"{csv_path}: CSV header is missing")
        fieldnames = reader.fieldnames
        if sort_by not in fieldnames:
            raise ValueError(f"{csv_path}: sort column {sort_by!r} is missing")
        rows = list(reader)

    rows.sort(
        key=lambda row: (
            _numeric_sort_key(row, sort_by),
            row.get("member", ""),
            row.get("experiment", ""),
        )
    )
    if "rank" in fieldnames:
        for rank, row in enumerate(rows, start=1):
            row["rank"] = str(rank)

    numeric_columns = {"rank", "public_rank", "public_delta"}
    alignment = [
        "---:" if name in numeric_columns or "prauc" in name else "---"
        for name in fieldnames
    ]
    source_name = csv_path.name
    lines = [
        "<!-- Generated by `python -m validation.render_leaderboard`; do not edit manually. -->",
        "",
        "# Validation leaderboard",
        "",
        f"Sorted by `{sort_by}` descending (higher is better). "
        f"Source: [{source_name}]({source_name}).",
        "",
        "| " + " | ".join(fieldnames) + " |",
        "| " + " | ".join(alignment) + " |",
    ]
    lines.extend(
        "| " + " | ".join(_markdown_cell(row.get(name, "")) for name in fieldnames) + " |"
        for row in rows
    )
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return markdown_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--sort-by", default=DEFAULT_SORT_COLUMN)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    destination = render_leaderboard(args.input, args.output, sort_by=args.sort_by)
    print(f"Rendered Markdown leaderboard: {destination}")


if __name__ == "__main__":
    main()
